feat(api) : #AMV2-265 create 3 Rest API to replace websockets
OPEN-ENT-NG/ressource-aggregator pull request #1
Opened 2022-03-30 13:06 UTC by aymericdevriesere

2022-03-30 14:45 UTC, sjollois requested changes
Super boulot de belle qualité! Quelques petites choses à revoir, mais dans l'ensemble c'est top! bravo beau travail!
N'hésites pas à me contacter si tu ne comprends pas mes commentaires :)

2022-03-30 14:45 UTC, sjollois commented on src/main/java/fr/openent/mediacentre/controller/WebSocketController.java
> +    public void favorites(String state, UserInfos user, ServerWebSocket ws) {
Pourquoi l'avoir rendu public ?

2022-03-30 14:45 UTC, sjollois commented on src/main/java/fr/openent/mediacentre/controller/WebSocketController.java
>                  ws.writeTextMessage(new JsonObject().put("error", "Unknown textbook action").put("status", "ko").encode());
pourquoi tu ne fais pas socketHelper.answerFailure ?

2022-03-30 14:45 UTC, sjollois commented on src/main/java/fr/openent/mediacentre/controller/WebSocketController.java
> +    private SocketHelper socketHelper;
ne surtout pas faire cela car plusieurs utilisateurs feront une requête ws en même temps!!

2022-03-30 14:45 UTC, sjollois commented on src/main/java/fr/openent/mediacentre/controller/WebSocketController.java
> +                            searchHelper.search(state, sources, expectedSources, data, userInfos, new SocketHelper(ws));
socketHelper déjà implémenté au dessus

2022-03-30 14:45 UTC, sjollois commented on src/main/java/fr/openent/mediacentre/helper/APIHelper.java
> +    private HttpServerRequest request;
idem il va y avoir plusieurs requêtes en même temps d'utilisateurs

2022-03-30 14:45 UTC, sjollois commented on src/main/java/fr/openent/mediacentre/helper/SocketHelper.java
> +        answerSuccess(answer);
Pourquoi il n'a pas de message d'erreurs ?

2022-03-30 14:45 UTC, sjollois commented on src/main/java/fr/openent/mediacentre/helper/SocketHelper.java
> +    private final ServerWebSocket ws;
Attention plusieurs requêts web socket d'utilisateurs différents

2022-03-30 15:03 UTC, aymericdevriesere commented on src/main/java/fr/openent/mediacentre/controller/WebSocketController.java
> +    public void favorites(String state, UserInfos user, ServerWebSocket ws) {
C'est une erreur c'est changé.

2022-03-30 15:03 UTC, aymericdevriesere commented on src/main/java/fr/openent/mediacentre/controller/WebSocketController.java
>                  ws.writeTextMessage(new JsonObject().put("error", "Unknown textbook action").put("status", "ko").encode());
Petit oubli je pensais l'avoir remplacé partout

2022-03-30 15:24 UTC, aymericdevriesere commented on src/main/java/fr/openent/mediacentre/helper/SocketHelper.java
> +        answerSuccess(answer);
Il n'y a pas de message d'erreur car il est contenu dans le JSON passé au websocket (alors que Renders possède une fonction spécifique au rendu des erreurs)

2022-03-30 15:29 UTC, aymericdevriesere commented on src/main/java/fr/openent/mediacentre/helper/FavoriteHelper.java
> +                                event.right().getValue()).encode());
fait

2022-03-30 15:29 UTC, aymericdevriesere commented on src/main/java/fr/openent/mediacentre/helper/SearchHelper.java
> +                answer.answerSuccess(new JsonObject().put("error", event.left().getValue()).put("status", "ko").encode());
Erreur bête

2022-03-30 15:30 UTC, aymericdevriesere commented on src/main/java/fr/openent/mediacentre/controller/WebSocketController.java
> +                            searchHelper.search(state, sources, expectedSources, data, userInfos, new SocketHelper(ws));
changé

2022-03-31 09:45 UTC, sjollois commented on src/main/java/fr/openent/mediacentre/helper/SocketHelper.java
> +        answerSuccess(answer);
à retravailler pour ne pas porter à confusion

2022-03-31 09:49 UTC, sjollois commented on src/main/java/fr/openent/mediacentre/controller/WebSocketController.java
>                  ws.writeTextMessage(new JsonObject().put("error", "Unknown textbook action").put("status", "ko").encode());
il en reste encore un dans la classe java

2022-03-31 10:12 UTC, sjollois approved these changes

2022-03-31 10:14 UTC, merged