feat(refacto): #MED-309 refacto of infinite scroll and filters
OPEN-ENT-NG/ressource-aggregator pull request #106
Opened 2024-07-04 14:18 UTC by niko-amosse

## Describe your changes

Each of our pages (except the home page) uses infinite scroll to display our cards, along with a filter.

These two elements were duplicated (with differences) across each of the pages.

The idea behind this refactoring is to create a component for our infinite scroll and also a unique component for our filter. These two components are configurable and adapt to the data provided as parameters.

This refactoring will be useful for the creation of our last two pages: bookmarks and favorites.

## Checklist tests

check that there is no regression of actual behavior

## Issue ticket number and link

[MED-309](https://jira.support-ent.fr/browse/MED-309)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-07-04 14:19 UTC, niko-amosse commented on frontend/src/components/drop-down/DropDown.tsx
ce composant est un dropdown de checkbox

2024-07-04 14:20 UTC, niko-amosse commented on frontend/src/components/filter-layout/FilterLayout.tsx
supprimé car il y a un maintenant un unique filtre

2024-07-04 14:20 UTC, niko-amosse commented on frontend/src/components/filter-resource-layout/FilterResourceLayout.tsx
supprimé car il y a un maintenant un unique filtre

2024-07-04 14:21 UTC, niko-amosse commented on frontend/src/components/filter-layout/FilterLayout.tsx
> -  const fetchFilters = useCallback(() => {
tout ça déplacé dans le composant DropDown qui est un dropdown de checkbox

2024-07-04 14:24 UTC, niko-amosse commented on frontend/src/components/filter-textbook-layout/FilterTextbookLayout.tsx
supprimé car il y a un maintenant un unique filtre

2024-07-04 14:25 UTC, niko-amosse commented on frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx
ce composant était déjà présent mais dupliqué sur chaque page, il est donc factorisé ici

2024-07-04 14:27 UTC, niko-amosse commented on frontend/src/hooks/useExternalResource.ts
la recupération des disciplines, levels et types se fait maintenant dans le hook useResourceListInfo

2024-07-04 14:27 UTC, niko-amosse commented on frontend/src/hooks/useExternalResource.ts
> +      ) as ExternalResource[];
on check le fameux is_textbook pour ajouter la ressource externe

2024-07-04 14:28 UTC, niko-amosse commented on frontend/src/hooks/useGlobal.ts
la recupération des disciplines, levels et types se fait maintenant dans le hook useResourceListInfo

2024-07-04 14:29 UTC, niko-amosse commented on frontend/src/hooks/useResourceListInfo.ts
ce composant prend une liste de ressources et donne plein d'info sur cette liste (utile pour les filtres)

2024-07-04 14:29 UTC, niko-amosse commented on frontend/src/hooks/useSearch.ts
la recupération des disciplines, levels et types se fait maintenant dans le hook useResourceListInfo

2024-07-04 14:29 UTC, niko-amosse commented on frontend/src/hooks/useTextbook.ts
la recupération des disciplines, levels et types se fait maintenant dans le hook useResourceListInfo

2024-07-04 14:30 UTC, niko-amosse commented on frontend/src/model/GlobalResource.model.ts
modif du nom pour respecter les conventions

2024-07-04 14:31 UTC, niko-amosse commented on frontend/src/model/SearchResultData.model.ts
plus utlisé car on a maintenant que des listes de ressources et pour scinder une liste avec textbook/externalResource/signet/moodle on utilise useResourceListInfo

2024-07-04 14:33 UTC, niko-amosse commented on frontend/src/routes/search/index.tsx
sur cette page au lieu d'avoir un énorme bloc qui contient notre filtre et le scroll infini, on a juste 2 composants, filtres et scroll infini (refacto) et suppression de disciplines, type, levels (plus utilisé)

2024-07-04 14:34 UTC, niko-amosse commented on frontend/src/routes/textbook/index.tsx
sur cette page au lieu d'avoir un énorme bloc qui contient notre filtre et le scroll infini, on a juste 2 composants, filtres et scroll infini (refacto) et suppression de disciplines, type, levels (plus utilisé)

2024-07-05 07:28 UTC, Mattox0 commented on frontend/src/components/filter-layout/FilterLayout.tsx
> +      filteredResources.push(...externalResources);
Pour ta culture React, on évite de push car ça modifie le tableau et oblige un re-render si il est appellé 
je te laisse lire la doc -> [https://fr.react.dev/learn/updating-arrays-in-state#updating-arrays-without-mutation](https://fr.react.dev/learn/updating-arrays-in-state#updating-arrays-without-mutation)

2024-07-05 07:31 UTC, Mattox0 commented on frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx
> +      console.log(visibleResources);
console.log a enlever

2024-07-05 07:34 UTC, Mattox0 commented on frontend/src/hooks/useExternalResource.ts
> +      const garResources: Resource[] = garResult?.data?.resources;
ajoute une sécurité si garResult renvoie une erreur 
`?? []`

2024-07-05 07:36 UTC, Mattox0 commented on frontend/src/hooks/useResourceListInfo.ts
> +  const [containSignet, setContainSignet] = useState<boolean>(false);
la liste de resources peut changer, tes contains doivent donc être des fonctions

2024-07-05 07:38 UTC, Mattox0 commented on frontend/src/hooks/useResourceListInfo.ts
> +  const [containSignet, setContainSignet] = useState<boolean>(false);
vu que tu les utilise ailleurs pour avoir cette info*

2024-07-05 07:40 UTC, Mattox0 commented on frontend/src/hooks/useResourceListInfo.ts
> +      }
tu veux récupérer toutes les infos ? 
Ici avec tes else if, il ne passera que dans le premier qui sera bon

2024-07-05 07:42 UTC, Mattox0 commented on frontend/src/hooks/useSearch.ts
> +        ...garResources,
a confirmer avec les PO mais cette ordre pour le search n'est pas le bon

2024-07-05 07:42 UTC, Mattox0 commented on frontend/src/hooks/useSearch.ts
> +        ...garResources,
si je me rappelle bien c'est GAR -> signet -> moodle

2024-07-05 07:43 UTC, Mattox0 commented on frontend/src/model/Textbook.model.ts
> -  is_textbook: boolean;
pourquoi tu le supprimes du model ?

2024-07-05 07:44 UTC, Mattox0 commented on frontend/src/model/Resource.model.ts
> +  is_textbook?: boolean;
is_textbook ne sera donné que pour les Textbook et/ou les ressources externes, aucune raison de le mettre pour tout le monde en facultatif

2024-07-05 07:45 UTC, niko-amosse commented on frontend/src/components/filter-layout/FilterLayout.tsx
> +      filteredResources.push(...externalResources);
yep je viens de voir ça, j'apprend un truc ! j'utilise concat du coup

2024-07-05 07:45 UTC, niko-amosse commented on frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx
> +      console.log(visibleResources);
fait

2024-07-05 07:46 UTC, niko-amosse commented on frontend/src/hooks/useExternalResource.ts
> +      const garResources: Resource[] = garResult?.data?.resources;
fait

2024-07-05 07:46 UTC, Mattox0 commented on frontend/src/routes/resources/index.tsx
> +  >([]); // all resources after the filters
tu as remis un tableau vide alors que j'avais mis des null exprès dans la refacto
de souvenir c'était pour gérer le loading screen, si tes ressources sont déjà défini, il ne s'affichera pas, si ?

2024-07-05 07:47 UTC, niko-amosse commented on frontend/src/hooks/useResourceListInfo.ts
> +  const [containSignet, setContainSignet] = useState<boolean>(false);
ils sont dans un useEffect qui prend en dépendance resources donc si resources change ils seront update ?

2024-07-05 07:48 UTC, Mattox0 commented on frontend/src/routes/search/index.tsx
> +    [],
idem

2024-07-05 07:49 UTC, niko-amosse commented on frontend/src/hooks/useResourceListInfo.ts
> +      }
c'est l'idée, en gros on parcours la liste des resources et on les tri dans chaque liste. par contre faut que je modifie mes push aussi ou pas besoin parce que c'est dans un hook ?

2024-07-05 07:50 UTC, Mattox0 commented on frontend/src/routes/resources/index.tsx
> +  >([]); // all resources after the filters
à discuter, ça pourrait avoir un impact et une grosse régression (a voir)

2024-07-05 07:50 UTC, Mattox0 requested changes
Beaucoup de choses à modif

2024-07-05 07:51 UTC, niko-amosse commented on frontend/src/hooks/useSearch.ts
> +        ...garResources,
cet ordre n'a pas d'importance le tri se fait dans le filtre

2024-07-05 07:52 UTC, Mattox0 commented on frontend/src/components/filter-layout/FilterLayout.tsx
> +      filteredResources.push(...externalResources);
plus que concat, tu peux utiliser ce qu'ils explique dans la doc
[...filteredResources, newItem]

2024-07-05 07:53 UTC, Mattox0 commented on frontend/src/hooks/useResourceListInfo.ts
> +  const [containSignet, setContainSignet] = useState<boolean>(false);
dans cette logique oui, mais c'est pas une bonne pratique dans ce cas

2024-07-05 07:54 UTC, Mattox0 commented on frontend/src/hooks/useResourceListInfo.ts
> +      }
tu peux modifier tes push, et oui c'est ce que je te dis
tu passeras dans ton else if que si celui d'au dessus ne passe pas

2024-07-05 07:56 UTC, niko-amosse commented on frontend/src/model/Resource.model.ts
> +  is_textbook?: boolean;
la recherche te renvoie une liste de Resource et donc les resources externes et manuels ne sont pas typé

2024-07-05 07:58 UTC, niko-amosse commented on frontend/src/routes/resources/index.tsx
> +  >([]); // all resources after the filters
les loadings apparaissent bien, il ne dépendant pas de si ta liste est null

2024-07-05 08:01 UTC, Mattox0 commented on frontend/src/routes/resources/index.tsx
> +              redirectLink="/resource"
notre route s'appelle "resources" et non resource

2024-07-05 09:11 UTC, ThomasSevagen commented on frontend/src/components/drop-down/DropDown.tsx
> +  const handleMultiCheckbox = (
Externaliser la logique de tri  dans une fonction que tu sortiras de ton composant

2024-07-05 09:17 UTC, ThomasSevagen commented on frontend/src/components/filter-layout/FilterLayout.tsx
> +  const [checkboxTextbook, setCheckboxTextbook] =
tu peux faire un seul state qui a pour type un objet, etant donné que tous ces states ont la même logique
`const [checkbox, useCheckbox]= useState<CheckBoxStateProps>(checkBoxInitialState)`
l'objet checkBoxInitialState devra être défini et externalisé en dehors de ton composant, ainsi que le type
`checkBoxInitialState={
check1:false,
check2:false,
....
}`

2024-07-05 09:47 UTC, ThomasSevagen commented on frontend/src/hooks/useResourceListInfo.ts
> +    setTextbooks(textbooksTemp);
Aller voir le useReducer :)

2024-07-08 07:35 UTC, niko-amosse commented on frontend/src/routes/resources/index.tsx
> +  >([]); // all resources after the filters
rajout des null et les loaders fonctionnent

2024-07-08 07:36 UTC, niko-amosse commented on frontend/src/routes/resources/index.tsx
> +              redirectLink="/resource"
modifié

2024-07-08 08:00 UTC, Mattox0 approved these changes

2024-07-08 09:00 UTC, merged