feat(modals): #MED-310 add modals to create, edit and delete pin resource
OPEN-ENT-NG/ressource-aggregator pull request #108
Opened 2024-07-09 15:34 UTC by Mattox0

## Describe your changes

Add 3 modals for create, delete or update a pin resource.

## Checklist tests

- Check if we can use 3 modals

## Issue ticket number and link

[MED-310](https://jira.support-ent.fr/browse/MED-310)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-07-09 17:11 UTC, JinDouang requested changes

2024-07-09 17:11 UTC, JinDouang commented on frontend/src/routes/app/index.tsx
> +              </div>
tu peux pas faire un composant pour l'empty state ?

2024-07-09 17:11 UTC, JinDouang commented on frontend/src/components/pins-carousel/PinsCarousel.scss
> +    background: #d9d9d9;
tu peux pas variabiliser cette valeur ?

2024-07-10 08:47 UTC, JinDouang approved these changes

2024-07-11 13:35 UTC, niko-amosse commented on frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx
> +  refetchSearch: () => void;
remettre refetchData

2024-07-11 13:38 UTC, niko-amosse commented on frontend/src/components/modals/create-pins/CreatePins.tsx
> +                currentTarget.src = "/mediacentre/public/img/no-avatar.svg";
mettre la nouvelle image de james

2024-07-11 13:39 UTC, niko-amosse commented on frontend/src/components/modals/edit-pins/EditPins.tsx
> +                currentTarget.src = "/mediacentre/public/img/no-avatar.svg";
idem nouvelle image de james

2024-07-11 13:39 UTC, niko-amosse commented on frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx
> +  refetchSearch,
idem

2024-07-11 13:39 UTC, niko-amosse commented on frontend/src/components/infinite-scroll-list/InfiniteScrollList.tsx
> +                    refetchSearch={refetchSearch}
idem

2024-07-11 13:41 UTC, niko-amosse commented on frontend/src/components/pins-carousel/PinsCarousel.tsx
> +              <PinsCarouselCard pin={pin} link={pin?.link ?? pin?.url ?? ""}/>
on peut faire ça direct dans le composant non ? (pour le link)

2024-07-11 13:42 UTC, niko-amosse commented on frontend/src/components/search-card/SearchCard.tsx
> +  refetchSearch: () => void;
idem

2024-07-11 13:43 UTC, niko-amosse commented on frontend/src/components/search-card/SearchCard.tsx
> +  refetchSearch,
idem

2024-07-11 13:46 UTC, niko-amosse commented on frontend/src/routes/resources/index.tsx
> +              refetchSearch={refetchSearch}
idem

2024-07-11 13:46 UTC, niko-amosse commented on frontend/src/routes/search/index.tsx
> +              refetchSearch={refetchSearch}
idem

2024-07-11 13:47 UTC, niko-amosse commented on frontend/src/routes/textbook/index.tsx
> +              refetchSearch={() => {
idem

2024-07-11 13:48 UTC, niko-amosse approved these changes

2024-07-11 14:12 UTC, Mattox0 commented on frontend/src/components/pins-carousel/PinsCarousel.tsx
> +              <PinsCarouselCard pin={pin} link={pin?.link ?? pin?.url ?? ""}/>
en soit oui, mais c'est plus pratique de le faire directement dans les props, sinon tu devrais faire le if partout dans la card

2024-07-11 14:17 UTC, merged