feat(websocket): MED-173 replace websockets with api call in favorite page
OPEN-ENT-NG/ressource-aggregator pull request #13
Opened 2023-03-30 16:21 UTC by alicedraillard

## Describe your changes
- replace websocket init and update calls
- add document_types in signet model to enable filter

## Checklist tests
use "favorites" page as usual

## Issue ticket number and link
[MED-173](https://jira.support-ent.fr/browse/MED-173)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-30 16:22 UTC, alicedraillard commented on package.json
> +    "@types/babel__traverse": "7.14.2",
used to enable node compilation

2023-03-31 09:16 UTC, Sofianebernoussi approved these changes

2023-03-31 09:59 UTC, qpic-cgi requested changes

2023-03-31 09:59 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/favorite.ts
> +        }, [])];
je ne comprend pas l'utilitée de ton reduce ici

2023-03-31 09:59 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/favorite.ts
> +            .then((favorites: Array<Resource>) => {
await + then  ? il faut choisir (dans le doute choisis then)

2023-03-31 10:04 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/favorite.ts
> +        });
c'était le fonctionnement existant, j'ai extrait la méthode pour ne pas avoir de duplication de code

2023-03-31 10:05 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/favorite.ts
> +    }, 15000, 0, false);
MAJ des favoris toutes les x secondes oui (je suis en train de changer pr que le nombre de s soit une config)

2023-03-31 10:06 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/favorite.ts
> +        }, [])];
daccord, mais pourquoi un reduce ici du coup ? étant donné qu'il y a cette instruction: `resources.push(resource);` ?

2023-03-31 10:07 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/favorite.ts
> +    }, 15000, 0, false);
tu ne répond pas à ma question 😄

2023-03-31 10:08 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/favorite.ts
> +        });
et c'est impossible que tu mettes `favorite.favorite = true;` dans ton foreach qui est en dessous ?

2023-03-31 10:10 UTC, alicedraillard commented on src/main/resources/public/ts/controllers/favorite.ts
> +    }, 15000, 0, false);
le but du ticket c'est de remplacer les websockets, qui par des appels API donc je reprends le meme comportement

2023-03-31 10:11 UTC, qpic-cgi commented on src/main/resources/public/ts/controllers/favorite.ts
> +    }, 15000, 0, false);
okey, je comprend ça marche.

2023-03-31 13:24 UTC, JinDouang requested changes

2023-03-31 13:24 UTC, JinDouang commented on src/main/resources/public/ts/controllers/favorite.ts
> +    function ($scope: Scope, route, FavoriteService: FavoriteService, $interval: IIntervalService) {
```suggestion
    function ($scope: Scope, route, favoriteService: FavoriteService, $interval: IIntervalService) {
```

2023-03-31 13:24 UTC, JinDouang commented on src/main/resources/public/ts/controllers/favorite.ts
> +            .then((favorites: Array<Resource>) => {
Je te propose cette implémentation avec await de pref si possible : 

```
       try {
           vm.favorites = await favoriteService.get();   
       } catch (e) {
           console.error("an error has occurred during fetching favorite ", e);
           let errorMessage : string = lang.translate("calendar.external.sync.error") + " " + ".";
           toasts.warning(errorMessage);
           vm.favorites = [];
       }
       $scope.safeApply();
```

tu gagnes + de ligne

2023-03-31 13:24 UTC, JinDouang commented on src/main/resources/public/ts/model/Resource.ts
> +    constructor(data: Resource) {
je veux bien qu'on regarde ensemble pour ce model

2023-03-31 13:24 UTC, JinDouang commented on src/main/resources/public/ts/services/FavoriteService.ts
> +        return await http.get(`/mediacentre/favorites`)
idem

2023-04-04 09:08 UTC, closed without merging