feat(featured_resources): #MED-357 create EventBus to send featured GAR resources
OPEN-ENT-NG/ressource-aggregator pull request #158
Opened 2024-11-27 13:32 UTC by Glama107

## Describe your changes

Création d'un service qui récupère les ressources mise en avant par la région dans MongoDB, les compares à celles auxquelles l'utilisateur à accès dans le GAR, et renvoie le résultat.

## Checklist tests

## Issue ticket number and link

https://jira.support-ent.fr/browse/MED-357

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-11-27 13:36 UTC, Mattox0 approved these changes

2024-11-27 13:38 UTC, Glama107 commented on backend/src/main/java/fr/openent/mediacentre/helper/TextBookHelper.java
> +            if (externalResources != null && !externalResources.isEmpty()) {
Fix d'un bug rencontré lors de tests en local (NullPointerException)

2024-11-27 14:17 UTC, niko-amosse commented on backend/src/main/java/fr/openent/mediacentre/controller/FeaturedResourcesController.java
> +                        log.error("[Mediacentre@FeaturedResourcesController::getFeaturedResources] Failed to get featured resources: " + e);
faut mettre e.getMessage()

2024-11-27 14:19 UTC, niko-amosse approved these changes

2024-11-27 17:05 UTC, qperie requested changes

2024-11-27 17:05 UTC, qperie commented on backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultFeaturedResourcesService.java
> +                .map(obj -> (JsonObject) obj)
comme au dessu

2024-11-27 17:05 UTC, qperie commented on backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultFeaturedResourcesService.java
> +                            .put(DESCRIPTION, mongoDescriptions.get(obj.getString(ID_RESSOURCE)));
vlauers par défaut

2024-11-28 08:00 UTC, Glama107 commented on backend/src/main/java/fr/openent/mediacentre/core/constants/Field.java
> +    public static final String URL_ACCES_RESSOURCE = "urlAccesRessource";
Je savais aha mais étant donné que le texte dans la string est en français, je l'ai écris en français aussi

2024-11-28 11:07 UTC, Glama107 commented on backend/src/main/java/fr/openent/mediacentre/controller/FeaturedResourcesController.java
> +        UserUtils.getUserInfos(eb, userId, user -> {
Le seul disposant d'un future à besoin du contexte de la request, qu'on à pas car on est dans un EventBus

2024-11-28 11:08 UTC, Glama107 commented on backend/src/main/java/fr/openent/mediacentre/service/impl/DefaultFeaturedResourcesService.java
> +                .onSuccess(promise::complete)
On peut map sur une Future

2024-11-28 15:16 UTC, qperie approved these changes

2024-11-28 15:39 UTC, merged