feat(websocket): MED-175 replace simple search websockets with api call
OPEN-ENT-NG/ressource-aggregator pull request #19
Opened 2023-04-21 09:43 UTC by alicedraillard

## Describe your changes
- simple search uses API call instead of websocket

## Checklist tests
- use simple search tool as usual

## Issue ticket number and link
[MED-175](https://jira.support-ent.fr/browse/MED-175)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-25 12:08 UTC, Alex-Delaveau commented on src/main/resources/public/ts/controllers/search.ts
> +        this.loaders = this.initSources(true);
Appel à "this.loaders = this.initSources(true);" dans la fonction initSearch et juste en dessous de l'appel à cette fonction

2023-04-25 12:44 UTC, qperie requested changes

2023-04-25 12:44 UTC, qperie commented on src/main/java/fr/openent/mediacentre/controller/SearchController.java
> +                    badRequest(request);
Un petit log.error() en plus peut être ?

2023-04-25 12:44 UTC, qperie commented on src/main/java/fr/openent/mediacentre/controller/SearchController.java
> +                    badRequest(request);
Idem que plus haut

2023-04-25 12:44 UTC, qperie commented on src/main/resources/public/template/search.html
> +    <infinite-scroll scrolled="vm.mainScope.mc.infiniteScroll()"></infinite-scroll>
Pourquoi ce changement ici et pas aux autres endroits du fichier où on utilise "mc" ?

2023-04-25 12:44 UTC, qperie commented on src/main/resources/public/ts/controllers/search.ts
> +        this.loaders = this.initSources(true);
Exact ça fait un doublon d'appel là

2023-04-25 12:44 UTC, qperie commented on src/main/resources/public/ts/controllers/search.ts
> +    private filter = (searchResources: Array<Resource>) => {
Com' global pour tout ce qui suit dans ce fichier : tu peux typer tes retours de fonctions et pas mal de variables

2023-04-25 12:44 UTC, qperie commented on src/main/resources/public/ts/controllers/search.ts
> +            sources: ["fr.openent.mediacentre.source.GAR", "fr.openent.mediacentre.source.Moodle", "fr.openent.mediacentre.source.PMB", "fr.openent.mediacentre.source.Signet"]
Hésite pas à en faire des constantes de ces valeurs, elles reviennent régulièrement j'ai l'impression

2023-04-26 08:09 UTC, alicedraillard commented on src/main/resources/public/template/search.html
> +    <infinite-scroll scrolled="vm.mainScope.mc.infiniteScroll()"></infinite-scroll>
C'est parce que j'ai réfacto le searchController et maintenant les données du mainController sont accessibles dans mainScope depuis le searchController

2023-04-26 09:01 UTC, Alex-Delaveau approved these changes

2023-04-26 09:13 UTC, qperie approved these changes

2023-04-26 09:25 UTC, merged