feat(global): #MED-219 add global ressources only access to parents
OPEN-ENT-NG/ressource-aggregator pull request #38
Opened 2024-03-13 16:34 UTC by Mattox0

## Describe your changes

We wanted to add global resources, accessible only to parents.
Now, we can create global resources, and parents can see they resources.

API documentation not yet done, but planned for the future.

## Checklist tests

- Create a global resource with `profiles: ["RELATIVE"]`
- Connect in parent account and check the external resource label
- Connect another account and we don't have global external resources

## Issue ticket number and link

[MED-219](https://jira.support-ent.fr/browse/MED-219)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [X] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-03-14 07:07 UTC, Rseuret approved these changes

2024-03-14 07:07 UTC, Rseuret commented on src/main/java/fr/openent/mediacentre/service/impl/GlobalResourceServiceMongoImpl.java
> +        mongo.delete(collection, new JsonObject().put("_id", idChannel), MongoDbResult.validResultHandler(FutureHelper.handlerJsonObject(promise)));
magic string

2024-03-15 16:26 UTC, qperie requested changes

2024-03-15 16:26 UTC, qperie commented
Ne pas oublier les TU + documentation Swagger sur Confluence aussi !

2024-03-19 13:18 UTC, qperie approved these changes

2024-03-19 13:23 UTC, merged