fix(home page): #MED-272 new display on home page
OPEN-ENT-NG/ressource-aggregator pull request #78
Opened 2024-06-11 11:35 UTC by niko-amosse

## Describe your changes

![image](https://github.com/OPEN-ENT-NG/ressource-aggregator/assets/85460454/b9266c07-9a92-4054-8a60-027f2b7f94f1)

change home display for different cases of empty list (favorite, manual, etc) and add an empty state

## Checklist tests

check the display with different combinaison of empty list
check the responsive

## Issue ticket number and link

[MED-272](https://jira.support-ent.fr/browse/MED-272)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-06-11 15:36 UTC, JinDouang requested changes

2024-06-11 15:36 UTC, JinDouang commented on frontend/src/hooks/useTextbook.ts
> +          textbook.document_types?.includes("livre numérique") ?? false,
je peux pas accepter ça

de ce que je comprends, vous reprenez une fonctionnalité déjà existante en angularjs, montrez le code/commit

Si, une règle de gestion s'est rajouté, je veux les specs dans le ticket montrant explicitement que "livre numérique", c'est "manuel"

2024-06-11 15:36 UTC, JinDouang commented on frontend/src/hooks/useTextbook.ts
> +          !externalResource.document_types?.includes("livre numérique") ??
idem

2024-06-11 15:53 UTC, alicedraillard commented on frontend/src/components/list-card/ListCard.scss
> +      height: 680px;
Pour toutes les valeurs en dur : OK pour le responsive ?

2024-06-11 15:53 UTC, alicedraillard commented on frontend/src/styles/page/home.scss
> +        gap: 20px;
idem pr les valeurs en dur : ok responsive ?

2024-06-12 07:20 UTC, niko-amosse commented on frontend/src/components/list-card/ListCard.scss
> +      height: 680px;
oui c'est testé

2024-06-12 07:20 UTC, niko-amosse commented on frontend/src/styles/page/home.scss
> +        gap: 20px;
idem testé

2024-06-12 17:25 UTC, merged